[tool.poetry]
name = "jetedmd-experiments"
version = "0.1.0"
description = "Experimental template for system identification benchmarks using dynid_benchmark."
authors = ["Tomoki Uda <tomoki.uda@gmail.com>", "Isao Ishikawa"]
license = "MIT"
readme = "README.md"
packages = [{ include = "dynid_benchmark" }]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
numpy = ">=1.20,<1.27"
scipy = ">=1.6,<1.12"
scikit-learn = "1.1.3"
matplotlib = "3.5.0"
pyyaml = ">=6.0"
pykoopman = "1.1.0"
pydmd = "0.4.1"
derivative = "0.6.0"
optht = "0.2.0"
prettytable = "3.9.0"
torch = "2.1.0"
lightning = "2.0.9"
setuptools = ">=65,<81"

[tool.poetry.group.pysindy.dependencies]
pysindy = "^1.7"

[tool.poetry.group.dev.dependencies]
black = "^25.9.0"
pytest = "^8.4.2"

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"
